services:
  - type: web
    name: calculadora-sugar
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
    headers:
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self' 'unsafe-inline' 'unsafe-eval' https: http: data: blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https: http:; style-src 'self' 'unsafe-inline' https: http:; img-src 'self' data: https: http: blob:; font-src 'self' https: http: data:;"
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*.js
        name: Content-Type
        value: application/javascript
      - path: /*.css
        name: Content-Type
        value: text/css
      - path: /*.json
        name: Content-Type
        value: application/json 